language: objective-c
osx_image: xcode7
before_script:
- brew update
- brew install carthage
script:
   - xctool -project SwiftIO.xcodeproj -scheme SwiftIO_OSX build test
   - xctool -project SwiftIO.xcodeproj -scheme SwiftIO_iOS -sdk iphonesimulator build test
