language: objective-c
osx_image: xcode8
before_script:
- carthage bootstrap --no-use-binaries
script:
- xcodebuild -project SwiftIO.xcodeproj -scheme SwiftIO_iOS -sdk iphonesimulator build
- xcodebuild -project SwiftIO.xcodeproj -scheme SwiftIO_OSX build
- xcodebuild -project SwiftIO.xcodeproj -scheme TestApp build

